services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    ports:
      - 4000:4000
    volumes:
      - ./:/home/nodeuser/app
    environment:
      - NODE_ENV=development
      - PORT=4000
    tty: true
    stdin_open: true
    init: true
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
